indiaelections/urls.py
from django.conf import settings
from django.conf.urls import url
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from django.views.decorators.cache import cache_page
from rest_framework_simplejwt import views as jwt_views

from core import views

TEN_MINUTES = 60 * 10
THIRTY_MINUTES = 60 * 30
FOREVER = 24 * 60 * 60 * 30

urlpatterns = [
    url(r'^$', cache_page(TEN_MINUTES)(views.index), name="home"),
    url(r'^terms-and-conditions', cache_page(FOREVER)(views.terms_and_conditions), name="tandc"),
    url(r'^admin/', admin.site.urls),
    # url(r'', views.hello_world),
    # url(r'^poc/', cache_page(600)(views.POC.as_view()), name='poc'),
    url(r'^india/', cache_page(TEN_MINUTES)(views.index), name='index'),
    url(r'^tn/', cache_page(THIRTY_MINUTES)(views.tn), name='tn'),
    url(r'^wordcloud/', cache_page(600)(views.get_word_cloud), name="get-word-cloud"),
    path('api/token/', jwt_views.TokenObtainPairView.as_view(), name='token_obtain_pair'),
    path('api/token/refresh/', jwt_views.TokenRefreshView.as_view(), name='token_refresh'),
    url(r'^poll/', include('poll.urls')),
    url(r'^job/', include('core.job.urls')),
    url(r'^view/', cache_page(TEN_MINUTES)(views.whatsup_with_tweets), name="view-wordcloud")
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

poll/urls.py
from django.conf.urls import url

from . import views

urlpatterns = [
    url(r'^opinion-poll/', views.opinion_poll, name='opinion-poll'),

    url(r'^ajax/load-places/', views.load_constituencies, name="opinion-poll-load-places"),
]

poll/models.py
from django.core.validators import MinValueValidator
from django.db import models

from .constants import OPINION_POLL_OPTIONS, GENDER


class IFrameEnabledSites(models.Model):
    domain = models.CharField(max_length=100, unique=True, db_index=True)
    enabled = models.BooleanField(default=False)

    def __str__(self):
        return "IFrame for site {} enabled: {}".format(self.domain, self.enabled)


class StateUnion(models.Model):
    name = models.CharField(max_length=30)

    def __str__(self):
        return self.name


class Constituency(models.Model):
    state_union = models.ForeignKey(StateUnion, on_delete=models.CASCADE)
    name = models.CharField(max_length=30)

    def __str__(self):
        return self.name


class OpinionPoll(models.Model):
    email = models.EmailField(max_length=100, unique=True, blank=False, null=False, db_index=True)
    choices = models.CharField(max_length=1, choices=OPINION_POLL_OPTIONS, blank=False, null=False)
    age = models.PositiveSmallIntegerField(blank=False, validators=[MinValueValidator(18)])
    gender = models.CharField(max_length=1, choices=GENDER, blank=False, null=False)
    state = models.ForeignKey(StateUnion, on_delete=models.SET_NULL, blank=False, null=True)
    place = models.ForeignKey(Constituency, on_delete=models.SET_NULL, blank=False, null=True)
    ip_address = models.GenericIPAddressField()
    added_time = models.DateTimeField(auto_now_add=True)

poll/forms.py
from django import forms

from .models import OpinionPoll, Constituency


class OpinionPollForm(forms.ModelForm):

    class Meta:
        model = OpinionPoll
        fields = ('email', 'age', 'gender', 'state', 'place', 'choices')

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['place'].queryset = Constituency.objects.none()

        if 'state' in self.data:
            try:
                state_id = int(self.data.get('state'))
                self.fields['place'].queryset = Constituency.objects.filter(state_union_id=state_id).order_by('name')
            except (ValueError, TypeError):
                pass
        elif self.instance.pk:
            self.fields['place'].queryset = self.instance.state.constituency_set.order_by('name')

poll/views.py
from django.contrib import messages
from django.shortcuts import get_object_or_404, render
from django.views.decorators.clickjacking import xframe_options_exempt
from django.views.decorators.csrf import csrf_exempt

from .constants import GOOGLE_RECAPTCHA_SITE_KEY
from .forms import OpinionPollForm
from .models import Constituency, IFrameEnabledSites
from .utils import get_ip_address, verify_recaptcha


@csrf_exempt
@xframe_options_exempt
def opinion_poll(request):
    get_object_or_404(IFrameEnabledSites, domain=request.META["HTTP_HOST"], enabled=True)

    form = OpinionPollForm()

    if request.method == "POST":
        form = OpinionPollForm(request.POST)

        if form.is_valid() and verify_recaptcha(request):
            try:
                voter = form.save(commit=False)
                voter.ip_address = get_ip_address(request)
                voter.save()
                messages.success(request, 'Your opinion was saved. Results will be published on May 3rd week.')
            except Exception:
                messages.error(request, "Unable to save your opinion. Please try again after some time.")

    return render(
        request,
        template_name='poll.html',
        context={
            'form': form,
            'google_recaptcha_site_key': GOOGLE_RECAPTCHA_SITE_KEY})

@csrf_exempt
def load_constituencies(request):
    state_id = request.GET.get('state')
    constituencies = Constituency.objects.filter(state_union_id=state_id).order_by('name')
    return render(request, 'places.html', {'places': constituencies})

poll/templates/places.html
<option value="">---------</option>
{% for place in places %}
<option value="{{ place.pk }}">{{ place.name }}</option>
{% endfor %}

poll/templates/poll.html
{% extends "base.html" %}
{% load crispy_forms_tags %}
{% block content %}

<center>

    <h2> Opinion Poll </h2>
    {% if messages %}
    <ul class="messages">
        {% for message in messages %}
        <li
        {% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
        {% endfor %}
    </ul>
    {% endif %}
    <div class="container" style="width:300px;">
        <form method="POST" id="pollForm" data-places-url="{% url 'opinion-poll-load-places' %}">
            <div class="row">
                {% csrf_token %}
                {% for error in form.non_field_errors %}
                <div class="form-group has-errors text-danger small">
                    {{error}}
                </div>
                {% endfor %}
                {{ form|crispy }}
                <div class="g-recaptcha" data-sitekey="{{ google_recaptcha_site_key }}" required></div>
                <br/>
                <button type="submit" style="background-color:#1A94EF;color:white;" class="save btn btn-default">Vote
                </button>
            </div>
        </form>
    </div>
</center>

<script src="https://code.jquery.com/jquery-3.3.1.min.js"></script>
<script>
    $("#id_state").change(function () {
      var url = $("#pollForm").attr("data-places-url");
      var stateId = $(this).val();

      $.ajax({
        url: url,
        data: {
          'state': stateId
        },
        success: function (data) {
          $("#id_place").html(data);
        }
      });

    });

</script>
{% endblock %}